### ISSUE TITLE
Optimisation: Font Awesome

### ISSUE THREAD

**Issue by Triloworld** [OpenEmu/openemu.github.io#9]
We don't need that thing.
Right now, there is two (2) icons used:

fa fa-fw fa-chevron-right
fa fa-fw fa-download

It is better to use 2 SVG icon to replace full library and one connection will be removed.
Source of it: https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg
I can do it if other agree :)

**Comment by craigerskine** [comment]
It's coming from a CDN and it's cached. We include it in case we may need it for future updates. I'm not going to create a unique SVG for each new icon we may need. Ideally I'd like to use v5 and a kit so it only sends down the icons we are calling, but I'm not going to use my personal FA5 license on this.

We are fine using the free v4 cached CDN version since it's not hurting anything. If the CDN goes down the design will not be impacted or broken.

The pros of including the whole thing outweigh the cons.
